name: flutter_app
description: NTUT Life TAT, convenient, concise, fast, powerful, enrich your NTUT life!
publish_to: 'none'

# CHECK THE BUILD CODE BEFORE DISTRIBUTION!!
version: 1.6.9+5273

environment:
  flutter: ">=3.7.12 <4.0.0"
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # TAT 2 Core implementations, reference it to use some of the new features.
  # Use https login with GitHub personal access key at the first time to obtain this sub-package.
  tat_core:
    git:
      url: git@github.com:NTUT-NPC/TAT-Core.git
      ref: 7611fe96ff2bb7bb5341c742d94f869d86d33e1c # restricted by dart language version. (<3)

  path: ^1.8.2 # restricted by flutter sdk.
  path_provider: ^2.0.15
  provider: ^6.0.5
  url_launcher: ^6.1.11 # restricted by dart language version. (<3)
  logger: ^2.0.2+1
  sprintf: ^7.0.0
  flutter_local_notifications: ^16.1.0
  rxdart: ^0.27.7
  video_player: ^2.7.2
  chewie: ^1.5.0 # restricted by alice_lightweight 3.3.0
  html_unescape: ^2.0.0
  local_auth: ^2.1.6 # restricted by dart language version. (<3)
  version: ^3.0.2
  shared_preferences: ^2.2.2
  flutter_cache_manager: ^3.3.1
  dio: ^4.0.6 # restricted by feature. Upgrade pending for manually migration.
  dio_cookie_manager: ^2.0.0 # restricted by dio 4.0.6
  cookie_jar: ^3.0.1 # restricted by dio 4.0.6
  html: ^0.15.4
  github: ^9.19.0
  clipboard: ^0.1.3
  flutter_inappwebview: ^5.8.0
  flutter_web_browser:
    git:
      url: git@github.com:NEO-TAT/flutter_web_browser.git
      ref: master
  eva_icons_flutter: ^3.1.0
  flutter_feather_icons: ^2.0.0+1
  json_annotation: ^4.8.1
  back_button_interceptor: ^6.0.2 # restricted by flutter sdk.
  dart_big5: ^0.0.5
  flutter_widget_from_html_core: ^0.14.4
  flutter_staggered_animations: ^1.1.1
  flutter_downloader: ^1.10.5 # [DISCONTINUED] restricted by dart language version. (<3)
  permission_handler: ^11.0.1
  mime_type: ^1.0.0
  get: ^4.6.5 # restricted by dart language version. (<3)
  bot_toast: ^4.1.3
  cached_network_image: ^3.2.3 # restricted by dart language version. (<3)
  auto_size_text: ^3.0.0
  table_calendar: ^3.0.9
  fluttertoast: ^8.2.2
  awesome_dialog: ^3.1.0
  flutter_slidable: ^3.0.0
  flutter_spinkit: ^5.2.0
  flutter_markdown: ^0.6.15 # restricted by dart language version. (<3)
  numberpicker: ^2.1.2
  alice_lightweight: ^3.3.0 # restricted by dio 4.0.6
  open_filex: ^4.3.4
  modal_bottom_sheet: ^3.0.0-pre # restricted by flutter sdk. (package import conflict)
  email_validator: ^2.1.17
  weekday_selector: ^1.1.0
  device_info_plus: ^8.2.2 # restricted by alice_lightweight 3.3.0

  firebase_core: ^2.19.0
  firebase_analytics: ^10.6.1
  firebase_crashlytics: ^3.4.1
  firebase_remote_config: ^4.3.1
  firebase_messaging: ^14.7.1
  cloud_firestore: ^4.11.0
  firebase_auth: ^4.11.1

  meta: ^1.8.0 # restricted by flutter sdk.
  uuid: ^4.1.0
  intl_utils: ^2.8.5
  flutter_native_splash: ^2.2.19 # restricted by path 1.8.2
  connectivity_plus: ^5.0.2
  android_intent_plus: ^5.2.1
  package_info_plus: ^3.1.2

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  dependency_validator: ^3.2.3
  flutter_launcher_icons:
    git:
      url: https://github.com/fluttercommunity/flutter_launcher_icons.git
      ref: 006cb1ed53f969bf11816cde5b16dd520e1ee40e # feat: added support for android 13+ themed icons
  build_runner: ^2.3.3 # restricted by dart language version. (<3)
  json_serializable: ^6.6.2 # restricted by dart language version. (<3)
  flutter_lints: ^2.0.3 # restricted by dart language version. (<3)

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: TATFont
      fonts:
        - asset: assets/fonts/GenSenRounded-R.ttc
          weight: 400
        - asset: assets/fonts/GenSenRounded-B.ttc
          weight: 700

flutter_intl:
  # Because it will be repeatedly generated when it is turned on,
  # it is very troublesome, so we temporarily turn it off.
  # Run "flutter pub run intl_translation:extract_to_arb --output-dir=lib/l10n lib/l10n/intl_messages.dart" to generate it.
  enabled: false

flutter_launcher_icons:
  image_path: assets/images/original.png

  android: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/images/android.png # Android 8.0+ icons
  adaptive_icon_monochrome: assets/images/android.png # Android 13+ themed icons

  ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  branding: assets/images/branding.png

  color_dark: "#2b2b2b"
  image_dark: assets/images/splash-dark.png
  branding_dark: assets/images/branding-dark.png

  android_12:
    color: "#ffffff"
    image: assets/images/splash-android_12.png
    branding: assets/images/branding.png

    color_dark: "#2b2b2b"
    image_dark: assets/images/splash-android_12-dark.png
    branding_dark: assets/images/branding-dark.png

module:
  androidX: true
