name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  sqflite: ^1.2.0
  path: ^1.6.4
  provider: ^4.0.1
  path_provider : ^1.5.1
  font_awesome_flutter: ^8.5.0
  url_launcher: ^5.4.1
  shared_preferences: ^0.5.6
  bottomreveal: ^1.0.0
  cached_network_image: ^2.0.0
  sprintf: ^4.0.2
  pull_to_refresh: ^1.5.8
  #requests: ^3.0.3
  http: ^0.12.0+4
  fluttertoast: ^3.1.3
  html: ^0.14.0+3
  giffy_dialog: ^1.6.1
  awesome_dialog: ^0.1.1
  community_material_icon: ^3.5.95
  random_color: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  flutter_automation:


flutter_icons:
  android: true
  ios: true
  image_path: "assets/ui.icon/exclamation_mark_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/gif/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: MyIcon
      fonts:
        - asset: assets/fonts/MyIcon.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
