name: flutter_app
description: NTUT Life TAT, convenient, concise, fast, powerful, enrich your NTUT life!

# you can use this command to build both android app bundle and ios ipa:
# flutter clean && flutter build ios --split-debug-info=build/app/outputs/symbols --obfuscate && flutter build appbundle --split-debug-info=build/app/outputs/symbols --obfuscate --shrink
# follow the google play new policy in 2021, do not build apk but aab.
# CHECK THE BUILD CODE BEFORE DISTRIBUTION!!
version: 1.3.1+5008

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path: ^1.8.0
  provider: ^5.0.0
  path_provider: ^2.0.1
  url_launcher: ^6.0.2
  #開啟email phone url...
  logger: ^1.0.0
  #顯示Log
  sprintf: ^6.0.0
  flutter_local_notifications: ^5.0.0
  #通知欄  需修改android原始碼
  rxdart: ^0.25.0
  #通知欄有使用到
  video_player: ^2.0.2
  chewie: ^1.0.0
  android_intent: ^2.0.0
  device_info: ^2.0.0
  html_unescape: ^2.0.0
  #處理HTML特殊字
  local_auth: ^1.1.0
  #驗證身分指紋
  version: 1.2.0
  #版本比較
  file_picker: ^3.0.0
  #選擇android資料夾
  #----------store data----------#
  shared_preferences: ^2.0.5
  flutter_cache_manager: ^2.1.2
  #----------internet----------#
  dio: ^3.0.10
  #網路get post API
  dio_cookie_manager: 1.0.0
  #用於產生cookie_jar與dio接口
  cookie_jar: ^1.0.1
  #可儲存式cookies
  html: ^0.15.0
  #html解析器
  connectivity: ^3.0.3
  github: ^7.0.3
  bloc: ^7.0.0
  clipboard: ^0.1.3
  #剪貼簿
  #----------WebView----------#
  flutter_inappwebview: ^5.2.1
  #---------icon----------#
  eva_icons_flutter: ^3.0.0
  #https://akveo.github.io/eva-icons/#/
  #https://akveo.github.io/eva-icons/#/
  flutter_icons: 1.1.0
  #https://oblador.github.io/react-native-vector-icons/
  #---------json----------#
  json_annotation: ^4.0.1
  #----------other----------#
  back_button_interceptor: ^5.0.0
  #攔截返回鍵訊息
  charset_converter: ^2.0.0      #big5 decode encode
  intl: ^0.17.0
  #DateTime to String
  package_info: ^2.0.0
  #檢測app版本用於檢查更新
  #----------html viewer----------#
  flutter_widget_from_html_core: ^0.6.0-rc.2021031201
  #----------animation----------#
  flutter_staggered_animations: ^1.0.0
  #listView or gridView動畫
  #----------download----------#
  flutter_downloader: ^1.5.2
  #下載app更新
  open_file: ^3.1.0
  permission_handler: ^6.1.1
  mime_type: ^1.0.0
  #----------Widget----------#
  get: ^3.26.0
  bot_toast: ^4.0.1
  #提供ListView可下拉式更新並且可動態加載
  cached_network_image: ^2.5.1
  #用url顯示圖片
  auto_size_text: 2.1.0
  #課表顯示有用到
  table_calendar: ^2.3.3
  #顯示行事曆
  #語言切換用
  fluttertoast: ^8.0.3
  #Toast
  awesome_dialog: ^1.3.2
  #顯示Error時用到
  flutter_slidable: ^0.5.7
  #email使用可左右滑抽屜
  flutter_spinkit: ^5.0.0
  #等待動畫
  flutter_markdown: ^0.6.1
  numberpicker: ^2.0.1
  #選擇學期
  alice:
    git:
      url: https://github.com/morris13579/alice
  pretty_json: ^2.0.0

  # Firebase
  firebase_core: ^1.0.2
  firebase_analytics: ^7.1.1
  firebase_crashlytics: ^1.0.0
  firebase_remote_config: ^0.9.0-dev.0
  firebase_messaging: ^9.0.1

dependency_overrides:
  http_parser:
    path: plugins/http_parser


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  #flutter_automation: ^1.4.0
  #---------json----------#
  build_runner: ^1.12.2
  json_serializable: ^4.1.0


flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: MyIcon
      fonts:
        - asset: assets/fonts/MyIcon.ttf
    - family: MyFont
      fonts:
        - asset: fonts/GenSenRounded-R.ttc
          weight: 400
        - asset: fonts/GenSenRounded-B.ttc
          weight: 700

flutter_intl:
  enabled: true

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/ios-icon.png"
  image_path_android: "assets/launcher/android-icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"
